name: kernel_builder

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:

  KS_LINK: https://github.com/tracefs/android_kernel_xiaomi_mt6768/ -b nethunter
  Device: lancelot
  

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Sync recovery source and device tree
         run: |
             cd ~
             mkdir plox
             cd plox
             git clone $KS_LINK --depth=1 kernel
             cd kernel 
             git clone https://github.com/kdrag0n/proton-clang.git clang-llvm --depth=1 
         
       - name: Build
         run: |
              cd ~/plox/kernel
              mkdir outL
              export ARCH=arm64
              export SUBARCH=arm64
              export DTC_EXT=dtc
              make O=outL ARCH=arm64 nethunter_defconfig
              export PATH="~/plox/kernel/clang-llvm/bin:${PATH}"
              make -j50 O=outL \
                                    ARCH=arm64 \
                                    CC=clang \
                                    CROSS_COMPILE=~/plox/kernel/clang-llvm/bin/aarch64-linux-gnu- \
                                    CROSS_COMPILE_ARM32=~/plox/kernel/clang-llvm/bin/arm-linux-gnueabi- \
                                    LD=~/plox/kernel/clang-llvm/bin/ld.lld \
                                    NM=~/plox/kernel/clang-llvm/bin/llvm-nm \
                                    OBJCOPY=~/plox/kernel/clang-llvm/bin/llvm-objcopy
              bp=${PWD}/outL
              zip kernel.zip ${PWD}/outL/arch/arm64/boot/Image.gz-dtb
              cd /home/runner/plox/Recovery_builder/Recovery_builder/plox/Kernel
              ls
              
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: $Device.zip
            path: /home/runner/plox/Recovery_builder/Recovery_builder/plox/kernel/kernel.zip
            retention-days: 5
